MSP_DP_COMMANDS = {
    'MSP_DISPLAYPORT': 182,
    'MSP_DP_HEARTBEAT': 0,
    'MSP_DP_RELEASE': 1,
    'MSP_DP_CLEAR_SCREEN': 2,
    'MSP_DP_WRITE_STRING': 3,
    'MSP_DP_DRAW_SCREEN': 4,
    'MSP_DP_OPTIONS': 5,
    'MSP_DP_SYS': 6,
}
